stages:
  - update

update_external_repo:
  stage: update
  script:
    - git clone https://git.app.uib.no/dok/skrivehjelp.git
    - cd skrivehjelp
    - echo "Update from CI" >> update.log
    - git add update.log
    - git commit -m "Automated update from CI"
    - git push https://hausvik:${GITHUB_TOKEN}@github.com/hausvik/skrivehjelp.git
  only:
    - triggers